CREATE TABLE IF NOT EXISTS EMPRESA (
    ID SERIAL PRIMARY KEY,
    NOME VARCHAR(100),
    CAIXA_TOTAL DOUBLE PRECISION
    );

CREATE TABLE IF NOT EXISTS SETOR (
    ID SERIAL PRIMARY KEY,
    NOME VARCHAR(100),
    EMPRESA_ID INT REFERENCES EMPRESA(ID)
    );

CREATE TABLE IF NOT EXISTS FUNCIONARIO (
    ID SERIAL PRIMARY KEY,
    NOME VARCHAR(100),
    IDADE INT,
    GENERO VARCHAR(50),
    CARGO VARCHAR(50),
    SALARIO DOUBLE PRECISION,
    SETOR_ID INT REFERENCES SETOR(ID)
    );

CREATE TABLE IF NOT EXISTS BENEFICIOS (
    FUNCIONARIO_ID INT PRIMARY KEY REFERENCES FUNCIONARIO(ID),
    VALE_REFEICAO DOUBLE PRECISION,
    VALE_ALIMENTACAO DOUBLE PRECISION,
    PLANO_SAUDE DOUBLE PRECISION,
    PLANO_ODONTO DOUBLE PRECISION,
    PERCENTUAL_IRRF DOUBLE PRECISION,
    PERCENTUAL_INSS DOUBLE PRECISION
    );

CREATE TABLE IF NOT EXISTS PRODUTO (
    ID SERIAL PRIMARY KEY,
    NOME VARCHAR(100),
    PRECO_COMPRA DOUBLE PRECISION,
    PRECO_VENDA DOUBLE PRECISION,
    QUANTIDADE_ESTOQUE INT,
    EMPRESA_ID INT REFERENCES EMPRESA(ID)
    );


CREATE TABLE IF NOT EXISTS TRANSPORTADORA (
    ID SERIAL PRIMARY KEY,
    NOME VARCHAR(100),
    LOCAIS_ATENDIMENTO TEXT,
    EMPRESA_ID INT REFERENCES EMPRESA(ID)
    );

CREATE TABLE IF NOT EXISTS NEGOCIOSEMANDAMENTO (
    ID SERIAL PRIMARY KEY,
    TIPO VARCHAR(50) NOT NULL,
    STATUS VARCHAR(50) NOT NULL,
    DATA_INICIO DATE DEFAULT CURRENT_DATE,
    DATA_ULTIMA_ATUALIZACAO TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    VALOR_ESTIMADO DOUBLE PRECISION,
    EMPRESA_ID INT REFERENCES EMPRESA(ID)
    );


CREATE TABLE IF NOT EXISTS NEGOCIO_PRODUTO (
    NEGOCIO_ID INT REFERENCES NEGOCIOSEMANDAMENTO(ID),
    PRODUTO_ID INT REFERENCES PRODUTO(ID),
    PRIMARY KEY (NEGOCIO_ID, PRODUTO_ID)
    );


CREATE TABLE IF NOT EXISTS NEGOCIO_FUNCIONARIO (
    NEGOCIO_ID INT REFERENCES NEGOCIOSEMANDAMENTO(ID),
    FUNCIONARIO_ID INT REFERENCES FUNCIONARIO(ID),
    PRIMARY KEY (NEGOCIO_ID, FUNCIONARIO_ID)
    );

CREATE TABLE IF NOT EXISTS TRANSACAO_FINANCEIRA (
    ID SERIAL PRIMARY KEY,
    TIPO VARCHAR(20),
    VALOR DOUBLE PRECISION,
    DATA TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    DESCRICAO TEXT,
    EMPRESA_ID INT REFERENCES EMPRESA(ID)
    );

CREATE TABLE IF NOT EXISTS VENDAS_PROGRAMADAS (
    ID SERIAL PRIMARY KEY,
    DATA_VENDA DATE NOT NULL,
    VALOR_VENDA DOUBLE PRECISION NOT NULL,
    CUSTO_PRODUTO DOUBLE PRECISION NOT NULL,
    PRODUTO_ID INT REFERENCES PRODUTO(ID),
    EMPRESA_ID INT REFERENCES EMPRESA(ID)
    );