DROP TABLE IF EXISTS NEGOCIO_PRODUTO CASCADE;
DROP TABLE IF EXISTS NEGOCIO_FUNCIONARIO CASCADE;
DROP TABLE IF EXISTS VENDAS_PROGRAMADAS CASCADE;
DROP TABLE IF EXISTS TRANSACAO_FINANCEIRA CASCADE;
DROP TABLE IF EXISTS NEGOCIOSEMANDAMENTO CASCADE;
DROP TABLE IF EXISTS TRANSPORTADORA CASCADE;
DROP TABLE IF EXISTS PRODUTO CASCADE;
DROP TABLE IF EXISTS BENEFICIOS CASCADE;
DROP TABLE IF EXISTS FUNCIONARIO CASCADE;
DROP TABLE IF EXISTS SETOR CASCADE;
DROP TABLE IF EXISTS EMPRESA CASCADE;





CREATE TABLE IF NOT EXISTS EMPRESA (
    ID SERIAL PRIMARY KEY,
    NOME VARCHAR(100),
    CAIXA_TOTAL DOUBLE PRECISION
    );

CREATE TABLE IF NOT EXISTS SETOR (
    ID SERIAL PRIMARY KEY,
    NOME VARCHAR(100),
    EMPRESA_ID INT REFERENCES EMPRESA(ID)
    );

CREATE TABLE IF NOT EXISTS funcionario (
    id SERIAL PRIMARY KEY,
    nome VARCHAR(100) NOT NULL,
    dataNascimento DATE NOT NULL,
    genero VARCHAR(50),
    cargo VARCHAR(50),
    salario DOUBLE PRECISION NOT NULL,
    vale_refeicao DOUBLE PRECISION DEFAULT 0,
    vale_alimentacao DOUBLE PRECISION DEFAULT 0,
    plano_saude DOUBLE PRECISION DEFAULT 0,
    plano_odonto DOUBLE PRECISION DEFAULT 0,
    percentual_irrf DOUBLE PRECISION DEFAULT 0,
    percentual_inss DOUBLE PRECISION DEFAULT 0,
    bonificacao DOUBLE PRECISION DEFAULT 0,
    setor_id INT REFERENCES setor(id)
    );


CREATE TABLE IF NOT EXISTS BENEFICIOS (
    FUNCIONARIO_ID INT PRIMARY KEY REFERENCES FUNCIONARIO(ID),
    VALE_REFEICAO DOUBLE PRECISION,
    VALE_ALIMENTACAO DOUBLE PRECISION,
    PLANO_SAUDE DOUBLE PRECISION,
    PLANO_ODONTO DOUBLE PRECISION,
    PERCENTUAL_IRRF DOUBLE PRECISION,
    PERCENTUAL_INSS DOUBLE PRECISION
    );

CREATE TABLE IF NOT EXISTS PRODUTO (
    ID SERIAL PRIMARY KEY,
    NOME VARCHAR(100),
    PRECO_COMPRA DOUBLE PRECISION,
    PRECO_VENDA DOUBLE PRECISION,
    QUANTIDADE_ESTOQUE INT,
    EMPRESA_ID INT REFERENCES EMPRESA(ID)
    );


CREATE TABLE IF NOT EXISTS TRANSPORTADORA (
    ID SERIAL PRIMARY KEY,
    NOME VARCHAR(100),
    CONTATO VARCHAR(50),
    TELEFONE VARCHAR(50),
    REGIAO VARCHAR(50),
    EMPRESA_ID INT REFERENCES EMPRESA(ID)
    );

CREATE TABLE IF NOT EXISTS NEGOCIOSEMANDAMENTO (
    ID SERIAL PRIMARY KEY,
    TIPO VARCHAR(50) NOT NULL,
    STATUS VARCHAR(50) NOT NULL,
    DATA_INICIO DATE DEFAULT CURRENT_DATE,
    VALOR_ESTIMADO DOUBLE PRECISION,
    EMPRESA_ID INT REFERENCES EMPRESA(ID)
    );

CREATE TABLE IF NOT EXISTS TRANSACAO_FINANCEIRA (
    ID SERIAL PRIMARY KEY,
    TIPO VARCHAR(20),
    VALOR DOUBLE PRECISION,
    DATA TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    DESCRICAO TEXT,
    EMPRESA_ID INT REFERENCES EMPRESA(ID)
    );

CREATE TABLE IF NOT EXISTS VENDAS_PROGRAMADAS (
    ID SERIAL PRIMARY KEY,
    DATA_VENDA DATE NOT NULL,
    PRODUTO_ID INT REFERENCES PRODUTO(ID),
    QUANTIDADE INT,
    CONCLUIDA BOOLEAN DEFAULT FALSE,
    EMPRESA_ID INT REFERENCES EMPRESA(ID)
    );